CREATE TABLE IF NOT EXISTS collections(
    CollectionID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserID BIGINT NOT NULL,
    Name VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS lists(
    ListID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CollectionID BIGINT UNSIGNED NOT NULL,
    Name VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS listColumnsType(
    ListColumnTypeID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ListID BIGINT UNSIGNED NOT NULL,
    Name VARCHAR(300) NOT NULL,
    Type JSON NOT NULL
    CHECK (JSON_VALID(Type))
);

CREATE TABLE IF NOT EXISTS items(
    ItemID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ListID BIGINT UNSIGNED NOT NULL,
    Name VARCHAR(300) NOT NULL,
    URL VARCHAR(10000),
    Rating TINYINT UNSIGNED DEFAULT 0
);

CREATE TABLE IF NOT EXISTS customRowsItems(
    CustomRowItemsID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ItemID BIGINT UNSIGNED NOT NULL,
    ListColumnTypeID BIGINT UNSIGNED NOT NULL,
    Value VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
    UserID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(300) NOT NULL,
    Email VARCHAR(300) NOT NULL,
    Password VARCHAR(10000) NOT NULL,
    BypassRestriction BOOLEAN NOT NULL DEFAULT FALSE,
    IsAdmin BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS usersLostPassword(
    UserLostID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserID BIGINT UNSIGNED NOT NULL,
    Token VARCHAR(3000) NOT NULL,
    Time BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS userActivity(
    UserActivityID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserID BIGINT UNSIGNED DEFAULT NULL,
    Type VARCHAR(30) DEFAULT NULL,
    Time BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS listSorting(
    ListSortingID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ListID BIGINT UNSIGNED NOT NULL,
    Type VARCHAR(100) DEFAULT NULL,
    ReverseOrder BOOLEAN DEFAULT FALSE
);
