ALTER TABLE collections 
CHANGE UserID UserID BIGINT(20) UNSIGNED NOT NULL;

ALTER TABLE collections 
ADD CONSTRAINT user_foreign_key
FOREIGN KEY (UserID) REFERENCES users (UserID) 
ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE lists
ADD CONSTRAINT collection_foreign_key
FOREIGN KEY (CollectionID) REFERENCES collections(CollectionID)
ON DELETE CASCADE
ON UPDATE RESTRICT;

ALTER TABLE listColumnsType
ADD CONSTRAINT list_column_foreign_key
FOREIGN KEY (ListID) REFERENCES lists(ListID)
ON DELETE CASCADE
ON UPDATE RESTRICT;

ALTER TABLE items
ADD CONSTRAINT list_item_foreign_key
FOREIGN KEY (ListID) REFERENCES lists(ListID)
ON DELETE CASCADE
ON UPDATE RESTRICT;

ALTER TABLE customRowsItems
ADD CONSTRAINT item_custom_data_foreign_key
FOREIGN KEY (ItemID) REFERENCES items(ItemID)
ON DELETE CASCADE
ON UPDATE RESTRICT;

ALTER TABLE customRowsItems
ADD CONSTRAINT item_list_column_foreign_key
FOREIGN KEY (ListColumnTypeID) REFERENCES listColumnsType(ListColumnTypeID)
ON DELETE CASCADE
ON UPDATE RESTRICT;

ALTER TABLE userActivity
ADD CONSTRAINT user_activity_foreign_key
FOREIGN KEY (UserID) REFERENCES users(UserID)
ON DELETE CASCADE
ON UPDATE RESTRICT;

ALTER TABLE listSorting
ADD CONSTRAINT list_sorting_foreign_key
FOREIGN KEY (ListID) REFERENCES lists(ListID)
ON DELETE CASCADE
ON UPDATE RESTRICT;