const MAX_NUMBER_OF_LIST_PER_USER = 150;
const EXTENDED_NUMBER_OF_LIST_PER_USER = 500;

const MAX_NUMBER_OF_ITEMS = 150000;
const EXTENDED_MAX_NUMBER_OF_ITEMS = 500000;

const MAX_NUMBER_OF_CUSTOM_COLUMNS = 1000;
const EXTENDED_MAX_NUMBER_OF_CUSTOM_COLUMNS = 5000;

module.exports = {
    MAX_NUMBER_OF_LIST_PER_USER,
    EXTENDED_NUMBER_OF_LIST_PER_USER,
    MAX_NUMBER_OF_ITEMS,
    EXTENDED_MAX_NUMBER_OF_ITEMS,
    MAX_NUMBER_OF_CUSTOM_COLUMNS,
    EXTENDED_MAX_NUMBER_OF_CUSTOM_COLUMNS,
};
