services:
  gamesorting_webapp:
    image: bluedragon28/gamesorting_webapp
    build: ../
    ports:
      - 8080:8080
    environment:
      - ENV_VAR_FILE=/config_file/env.txt
    volumes:
      - /opt/gamesorting_webapp/app-config:/config_file
      - gamesorting_app_client_tmp_data:/app/clientData
    restart: always
    
    depends_on:
      gamesorting_mariadb:
        condition: service_healthy
  
  gamesorting_mariadb:
    image: mariadb:10
    volumes:
      - gamesorting_mariadb_data:/var/lib/mysql
      - /opt/gamesorting_webapp/mariadb/config_env:/config_file
      - /opt/gamesorting_webapp/mariadb/config:/etc/mysql/conf.d
    environment:
      - MARIADB_USER_FILE=/config_file/user
      - MARIADB_PASSWORD_HASH_FILE=/config_file/user_hash
      - MARIADB_ROOT_PASSWORD_HASH_FILE=/config_file/root_hash
      - MARIADB_DATABASE=gamesorting_webapp
    restart: always
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping",]
      timeout: 20s
      retries: 10

volumes:
  gamesorting_mariadb_data:
  gamesorting_app_client_tmp_data:
